/******************************************************************************
 *
 *  (C)Copyright 2005 - 2011 Marvell. All Rights Reserved.
 *
 *  THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF MARVELL.
 *  The copyright notice above does not evidence any actual or intended
 *  publication of such source code.
 *  This Module contains Proprietary Information of Marvell and should be
 *  treated as Confidential.
 *  The information in this file is provided for the exclusive use of the
 *  licensees of Marvell.
 *  Such users have the right to use, modify, and incorporate this code into
 *  products for purposes authorized by the license agreement provided they
 *  include this notice and the associated copyright notice with any such
 *  product.
 *  The information in this file is provided "AS IS" without warranty.
 
 ******************************************************************************/




/******************************************************************************
 *
 * Name:	ICU.h
 * Project:	Hermon-2
 * Purpose:	Testing
 *
 ******************************************************************************/


/******************************************************************************
 *
 * This file was automatically generated by reg.pl using  *	ICU.csv
 *
 ******************************************************************************/

/******************************************************************************
 *
 * History:
 *
 ********* PLEASE INSERT THE CVS HISTORY OF THE PREVIOUS VERSION HERE. *********
 *******************************************************************************/

#ifndef	__INC_ICU_H
#define	__INC_ICU_H

#include "platform_interrupts.h"

/*
 *
 *	THE BASE ADDRESSES
 *
 */
#define	ICU_BASE	0xD4282000

/*
 *
 *	THE REGISTER DEFINES
 *
 */
#define	ICU_INT_0_TO_63_CONF	(ICU_BASE+0x0000)	/* Interrupt 0 to 63
													 *			Configuration
													 *			Registers
													 *			Start
													 */
#define	ICU_CP_FIR_SEL_INT_NUM	(ICU_BASE+0x0100)	/* 32 bit	CP FIR Selected
													 *			Interrupt
													 *			Number
													 *			Register
													 */
#define	ICU_CP_IRQ_SEL_INT_NUM	(ICU_BASE+0x0104)	/* 32 bit	CP IRQ Selected
													 *			Interrupt
													 *			Number
													 *			Register
													 */
#define	ICU_AP_FIR_SEL_INT_NUM	(ICU_BASE+0x0108)	/* 32 bit	AP FIR Selected
													 *			Interrupt
													 *			Number
													 *			Register
													 */
#define	ICU_AP_IRQ_SEL_INT_NUM	(ICU_BASE+0x010C)	/* 32 bit	AP IRQ Selected
													 *			Interrupt
													 *			Number
													 *			Register
													 */
#define	ICU_CP_GBL_IRQ_MSK		(ICU_BASE+0x0110)	/* 32 bit	CP Global
													 *			Interrupt
													 *			Mask Register
													 */
#define	ICU_AP_GBL_IRQ_MSK		(ICU_BASE+0x0114)	/* 32 bit	AP Global
													 *			Interrupt
													 *			Mask Register
													 */
#define	ICU_DMA_CP_INT_MSK		(ICU_BASE+0x0118)	/* 32 bit	DMA CP
													 *			Interrupt
													 *			Mask Register
													 */
#define	ICU_DMA_AP_INT_MSK		(ICU_BASE+0x011C)	/* 32 bit	DMA AP
													 *			Interrupt
													 *			Mask Register
													 */
#define	ICU_DMA_CP_INT_STATUS	(ICU_BASE+0x0120)	/* 32 bit	DMA CP
													 *			Interrupt
													 *			Status
													 *			Register
													 */
#define	ICU_DMA_AP_INT_STATUS	(ICU_BASE+0x0124)	/* 32 bit	DMA AP
													 *			Interrupt
													 *			Status
													 *			Register
													 */
#define	ICU_INT_STATUS_0		(ICU_BASE+0x0128)	/* 32 bit	Interrupt
													 *			Status
													 *			Register 0 
													 */
#define	ICU_INT_STATUS_1		(ICU_BASE+0x012C)	/* 32 bit	Interrupt
													 *			Status
													 *			Register 1 
													 */
#define	ICU_VPRO_INT_MSK		(ICU_BASE+0x0130)	/* 32 bit	vPro Interrupt
													 *			Mask Register
													 */
#define	ICU_VPRO_INT_STATUS		(ICU_BASE+0x0134)	/* 32 bit	vPro Interrupt
													 *			Status
													 *			Register
													 */

/*
 *
 *	THE BIT DEFINES
 *
 */
/*	ICU_INT_0_TO_63_CONF	0x0000	Interrupt 0 to 63 Configuration Registers */
/*		Bit(s) ICU_INT_0_TO_63_CONF_RSRV_31_7 reserved */
/* AP Interrupt */
#define	ICU_INT_0_TO_63_CONF_AP_INT						BIT_6				
/* CP Interrupt */
#define	ICU_INT_0_TO_63_CONF_CP_INT						BIT_5				
/* IRQ/FIR */
#define	ICU_INT_0_TO_63_CONF_IRQ_FIR					BIT_4				
/* Priority/Masking */
#define	ICU_INT_0_TO_63_CONF_PRIORITY_MASKING_MSK		SHIFT0(0xf)			
#define	ICU_INT_0_TO_63_CONF_PRIORITY_MASKING_BASE		0

/*	ICU_CP_FIR_SEL_INT_NUM	0x0100	CP FIR Selected Interrupt Number Register */
/*		Bit(s) ICU_CP_FIR_SEL_INT_NUM_RSRV_31_7 reserved */
/* Interrupt Pending */
#define	ICU_CP_FIR_SEL_INT_NUM_INT_PENDING			BIT_6				
/* Selected Interrupt Number */
#define	ICU_CP_FIR_SEL_INT_NUM_SEL_INT_NUM_MSK		SHIFT0(0x3f)		
#define	ICU_CP_FIR_SEL_INT_NUM_SEL_INT_NUM_BASE		0

/*	ICU_CP_IRQ_SEL_INT_NUM	0x0104	CP IRQ Selected Interrupt Number Register */
/*		Bit(s) ICU_CP_IRQ_SEL_INT_NUM_RSRV_31_7 reserved */
/* Interrupt Pending */
#define	ICU_CP_IRQ_SEL_INT_NUM_INT_PENDING			BIT_6				
/* Selected Interrupt Number */
#define	ICU_CP_IRQ_SEL_INT_NUM_SEL_INT_NUM_MSK		SHIFT0(0x3f)		
#define	ICU_CP_IRQ_SEL_INT_NUM_SEL_INT_NUM_BASE		0

/*	ICU_AP_FIR_SEL_INT_NUM	0x0108	AP FIR Selected Interrupt Number Register */
/*		Bit(s) ICU_AP_FIR_SEL_INT_NUM_RSRV_31_7 reserved */
/* Interrupt Pending */
#define	ICU_AP_FIR_SEL_INT_NUM_INT_PENDING			BIT_6				
/* Selected Interrupt Number */
#define	ICU_AP_FIR_SEL_INT_NUM_SEL_INT_NUM_MSK		SHIFT0(0x3f)		
#define	ICU_AP_FIR_SEL_INT_NUM_SEL_INT_NUM_BASE		0

/*	ICU_AP_IRQ_SEL_INT_NUM	0x010C	AP IRQ Selected Interrupt Number Register */
/*		Bit(s) ICU_AP_IRQ_SEL_INT_NUM_RSRV_31_7 reserved */
/* Interrupt Pending */
#define	ICU_AP_IRQ_SEL_INT_NUM_INT_PENDING			BIT_6				
/* Selected Interrupt Number */
#define	ICU_AP_IRQ_SEL_INT_NUM_SEL_INT_NUM_MSK		SHIFT0(0x3f)		
#define	ICU_AP_IRQ_SEL_INT_NUM_SEL_INT_NUM_BASE		0

/*	ICU_CP_GBL_IRQ_MSK		0x0110	CP Global Interrupt Mask Register */
/*		Bit(s) ICU_CP_GBL_IRQ_MSK_RSRV_31_2 reserved */
#define	ICU_CP_GBL_IRQ_MSK_IRQ_MSK				BIT_1				/* Mask IRQ */
#define	ICU_CP_GBL_IRQ_MSK_FIR_MSK				BIT_0				/* Mask FIR */

/*	ICU_AP_GBL_IRQ_MSK		0x0114	AP Global Interrupt Mask Register */
/*		Bit(s) ICU_AP_GBL_IRQ_MSK_RSRV_31_2 reserved */
#define	ICU_AP_GBL_IRQ_MSK_IRQ_MSK				BIT_1				/* Mask IRQ */
#define	ICU_AP_GBL_IRQ_MSK_FIR_MSK				BIT_0				/* Mask FIR */

/*	ICU_DMA_CP_INT_MSK		0x0118	DMA CP Interrupt Mask Register */
/* DMA CP Interrupt Mask */
#define	ICU_DMA_CP_INT_MSK_DMA_CP_INT_MSK_MSK			SHIFT0(0xffffffff)	
#define	ICU_DMA_CP_INT_BASE_DMA_CP_INT_BASE_BASE		0

/*	ICU_DMA_AP_INT_MSK		0x011C	DMA AP Interrupt Mask Register */
/* DMA AP Interrupt Mask */
#define	ICU_DMA_AP_INT_MSK_DMA_AP_INT_MSK_MSK			SHIFT0(0xffffffff)	
#define	ICU_DMA_AP_INT_BASE_DMA_AP_INT_BASE_BASE		0

/*	ICU_DMA_CP_INT_STATUS	0x0120	DMA CP Interrupt Status Register */
/* DMA CP Interrupt Status */
#define	ICU_DMA_CP_INT_STATUS_DMA_CP_INT_STATUS_MSK			SHIFT0(0xffffffff)	
#define	ICU_DMA_CP_INT_STATUS_DMA_CP_INT_STATUS_BASE		0

/*	ICU_DMA_AP_INT_STATUS	0x0124	DMA AP Interrupt Status Register */
/* DMA Interrupt 1 Status */
#define	ICU_DMA_AP_INT_STATUS_DMA_INT1_STATUS_MSK		SHIFT0(0xffffffff)	
#define	ICU_DMA_AP_INT_STATUS_DMA_INT1_STATUS_BASE		0

/*	ICU_INT_STATUS_0		0x0128	Interrupt Status Register 0 */
/* Interrupt Status [31:0] */
#define	ICU_INT_STATUS_0_INT_STATUS_0_MSK		SHIFT0(0xffffffff)	
#define	ICU_INT_STATUS_0_INT_STATUS_0_BASE		0

/*	ICU_INT_STATUS_1		0x012C	Interrupt Status Register 1 */
/* Interrupt Status [63:32] */
#define	ICU_INT_STATUS_1_INT_STATUS_1_MSK		SHIFT0(0xffffffff)	
#define	ICU_INT_STATUS_1_INT_STATUS_1_BASE		0

/*	ICU_VPRO_INT_MSK		0x0130	vPro Interrupt Mask Register */
/*		Bit(s) ICU_VPRO_INT_MSK_RSRV_31_6 reserved */
/* VPro SEM Interrupt Mask */
#define	ICU_VPRO_INT_MSK_VPRO_SEM_INT_MSK_MSK			SHIFT3(0x7)			
#define	ICU_VPRO_INT_BASE_VPRO_SEM_INT_BASE_BASE		3
/* VPro DMA Interrupt Mask */
#define	ICU_VPRO_INT_MSK_VPRO_DMA_INT_MSK_MSK			SHIFT0(0x7)			
#define	ICU_VPRO_INT_BASE_VPRO_DMA_INT_BASE_BASE		0

/*	ICU_VPRO_INT_STATUS		0x0134	vPro Interrupt Status Register */
/*		Bit(s) ICU_VPRO_INT_STATUS_RSRV_31_6 reserved */
/* VPro SEM Interrupt Status */
#define	ICU_VPRO_INT_STATUS_VPRO_SEM_INT_STATUS_MSK			SHIFT3(0x7)			
#define	ICU_VPRO_INT_STATUS_VPRO_SEM_INT_STATUS_BASE		3
/* VPro DMA Interrupt Status */
#define	ICU_VPRO_INT_STATUS_VPRO_DMA_INT_STATUS_MSK			SHIFT0(0x7)			
#define	ICU_VPRO_INT_STATUS_VPRO_DMA_INT_STATUS_BASE		0



/* -------------------- */


#endif	/* __INC_ICU_H */
