@******************************************************************************
@**
@**  COPYRIGHT (C) 2011 Marvell Corporation.
@**	 All Rights Reserved
@**
@**  FILENAME:	predefines.inc
@**
@**  PURPOSE: 	Predefined values required for startup code
@**                  
@******************************************************************************
@

    .equ BIT_0,(1 << 0)
    .equ  BIT_1,(1 << 1)
    .equ  BIT_2,(1 << 2)
    .equ  BIT_3,(1 << 3)
    .equ  BIT_4,(1 << 4)
    .equ  BIT_5,(1 << 5)
    .equ  BIT_6,(1 << 6)
    .equ  BIT_7,(1 << 7)
    .equ  BIT_8,(1 << 8)
    .equ  BIT_9,(1 << 9)
   .equ  BIT_10,(1 << 10)
   .equ  BIT_11,(1 << 11)
   .equ  BIT_12,(1 << 12)
   .equ  BIT_13,(1 << 13)
   .equ  BIT_14,(1 << 14)
   .equ  BIT_15,(1 << 15)
   .equ  BIT_16,(1 << 16)
   .equ  BIT_17,(1 << 17)
   .equ  BIT_18,(1 << 18)
   .equ  BIT_19,(1 << 19)
   .equ  BIT_20,(1 << 20)
   .equ  BIT_21,(1 << 21)
   .equ  BIT_22,(1 << 22)
   .equ  BIT_23,(1 << 23)
   .equ  BIT_24,(1 << 24)
   .equ  BIT_25,(1 << 25)
   .equ  BIT_26,(1 << 26)
   .equ  BIT_27,(1 << 27)
   .equ  BIT_28,(1 << 28)
   .equ  BIT_29,(1 << 29)
   .equ  BIT_30,(1 << 30)
   .equ  BIT_31,(1 << 31)

	
