;******************************************************************************
;**
;**  COPYRIGHT (C) 2011 Marvell Corporation.
;**	 All Rights Reserved
;**
;**  FILENAME:	predefines.inc
;**
;**  PURPOSE: 	Predefined values required for startup code
;**                  
;******************************************************************************
;

BIT_0    EQU (1 << 0)
BIT_1    EQU  (1 << 1)
BIT_2    EQU  (1 << 2)
BIT_3    EQU  (1 << 3)
BIT_4    EQU  (1 << 4)
BIT_5    EQU  (1 << 5)
BIT_6    EQU  (1 << 6)
BIT_7    EQU  (1 << 7)
BIT_8    EQU  (1 << 8)
BIT_9    EQU  (1 << 9)
BIT_10   EQU  (1 << 10)
BIT_11   EQU  (1 << 11)
BIT_12   EQU  (1 << 12)
BIT_13   EQU  (1 << 13)
BIT_14   EQU  (1 << 14)
BIT_15   EQU  (1 << 15)
BIT_16   EQU  (1 << 16)
BIT_17   EQU  (1 << 17)
BIT_18   EQU  (1 << 18)
BIT_19   EQU  (1 << 19)
BIT_20   EQU  (1 << 20)
BIT_21   EQU  (1 << 21)
BIT_22   EQU  (1 << 22)
BIT_23   EQU  (1 << 23)
BIT_24   EQU  (1 << 24)
BIT_25   EQU  (1 << 25)
BIT_26   EQU  (1 << 26)
BIT_27   EQU  (1 << 27)
BIT_28   EQU  (1 << 28)
BIT_29   EQU  (1 << 29)
BIT_30   EQU  (1 << 30)
BIT_31   EQU  (1 << 31)

	END
