/******************************************************************************
 *
 * Name:	APBC.h
 * Project:	MMP2 ( PXA328 )
 * Purpose:	Testing
 *
 ******************************************************************************/

/******************************************************************************
 *
 *  (C)Copyright 2005 - 2011 Marvell. All Rights Reserved.
 *  
 *  THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF MARVELL.
 *  The copyright notice above does not evidence any actual or intended 
 *  publication of such source code.
 *  This Module contains Proprietary Information of Marvell and should be
 *  treated as Confidential.
 *  The information in this file is provided for the exclusive use of the 
 *  licensees of Marvell.
 *  Such users have the right to use, modify, and incorporate this code into 
 *  products for purposes authorized by the license agreement provided they 
 *  include this notice and the associated copyright notice with any such
 *  product. 
 *  The information in this file is provided "AS IS" without warranty.
 *
 ******************************************************************************/

/******************************************************************************
 *
 * This file was automatically generated by reg.pl using  *	APBC.csv
 *
 ******************************************************************************/

/******************************************************************************
 *
 * History:
 *
 ********* PLEASE INSERT THE CVS HISTORY OF THE PREVIOUS VERSION HERE. *********
 *******************************************************************************/

#ifndef	__INC_APBC_H
#define	__INC_APBC_H


/*
 *
 *	THE BASE ADDRESSES
 *
 */
#define	APBC_BASE	0xD4015000

#define	APBC_SSP2_CLK_RST		(APBC_BASE+0x004C)	// 32 bit	Clock/Reset


/*
 *
 *	THE REGISTER DEFINES
 *
 */
#define	APBC_TWSI_CLK_RST		(APBC_BASE+0x002c)	/* 32 bit	Clock/Reset
													 *			Control
													 *			Register for
													 *			TWSI
													 */

#define	APBC_GPIO_CLK_RST		(APBC_BASE+0x0008)	/* 32 bit	Clock/Reset
													 *			Control
													 *			Register for
													 *			GPIO
													 */

#define	APBC_IPC_CLK_RST		(APBC_BASE+0x0024)	/* 32 bit	Clock/Reset
													 *			Control
													 *			Register for
													 *			IPC
													 */
#define	APBC_TIMERS1_CLK_RST	(APBC_BASE+0x0034)	/* 32 bit	Clock/Reset
													 *			Control
													 *			Register for
													 *			Timer 1 
													 */

#define APBC_UART0_CLK_RST 		(APBC_BASE + 0x00)
#define APBC_KPC_CLK_RST		(APBC_BASE + 0x30)
#define APBC_AIB_CLK_RST		(APBC_BASE + 0x3C)
/*	APBC_IPC_CLK_RST		0x0024	Clock/Reset Control Register for IPC */
/*		Bit(s) APBC_IPC_CLK_RST_RSRV_31_7 reserved */
/* Functional Clock Select */
#define	APBC_IPC_CLK_RST_FNCLKSEL_MSK		SHIFT4(0x7)			
#define	APBC_IPC_CLK_RST_FNCLKSEL_BASE		4
/*		Bit(s) APBC_IPC_CLK_RST_RSRV_3 reserved */
/* IPC Reset Generation */
#define	APBC_IPC_CLK_RST_RST				BIT_2				
/* IPC Functional Clock Enable/Disable */
#define	APBC_IPC_CLK_RST_FNCLK				BIT_1				
/* IPC APB Bus Clock Enable/Disable */
#define	APBC_IPC_CLK_RST_APBCLK				BIT_0				


/*	APBC_TIMERS1_CLK_RST	0x0034	Clock/Reset Control Register for Timer 1 */
/*		Bit(s) APBC_TIMERS1_CLK_RST_RSRV_31_7 reserved */
/* Functional Clock Select */
#define	APBC_TIMERS1_CLK_RST_FNCLKSEL_MSK		SHIFT4(0x7)			
#define	APBC_TIMERS1_CLK_RST_FNCLKSEL_BASE		4
/*		Bit(s) APBC_TIMERS1_CLK_RST_RSRV_3 reserved */
/* Timers Reset Generation */
#define	APBC_TIMERS1_CLK_RST_RST				BIT_2				
/* Timers Functional Clock Enable/Disable */
#define	APBC_TIMERS1_CLK_RST_FNCLK				BIT_1				
/* Timers APB Bus Clock Enable/Disable */
#define	APBC_TIMERS1_CLK_RST_APBCLK				BIT_0				



#endif	/* __INC_APBC_H */
