/******************************************************************************
 *
 * Name:	CIU.h
 * Project:	Hermon-2
 * Purpose:	Testing
 *
 ******************************************************************************/

/******************************************************************************
 *
 *  (C)Copyright 2005 - 2011 Marvell. All Rights Reserved.
 *  
 *  THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF MARVELL.
 *  The copyright notice above does not evidence any actual or intended 
 *  publication of such source code.
 *  This Module contains Proprietary Information of Marvell and should be
 *  treated as Confidential.
 *  The information in this file is provided for the exclusive use of the 
 *  licensees of Marvell.
 *  Such users have the right to use, modify, and incorporate this code into 
 *  products for purposes authorized by the license agreement provided they 
 *  include this notice and the associated copyright notice with any such
 *  product. 
 *  The information in this file is provided "AS IS" without warranty.
 *
 ******************************************************************************/

/******************************************************************************
 *
 * This file was automatically generated by reg.pl using  *	CIU.csv
 *
 ******************************************************************************/

/******************************************************************************
 *
 * History:
 *
 ********* PLEASE INSERT THE CVS HISTORY OF THE PREVIOUS VERSION HERE. *********
 *******************************************************************************/

#ifndef	__INC_CIU_H
#define	__INC_CIU_H


/*
 *
 *	THE BASE ADDRESSES
 *
 */
#define	CIU_BASE	0xD4282C00

/*
 *
 *	THE REGISTER DEFINES
 *
 */
#define	CHIP_ID				(CIU_BASE+0x0000)	/* 32 bit	Chip ID Register */
#define	CP_CPU_CONF			(CIU_BASE+0x0004)	/* 32 bit	CP CPU
												 *			Configuration
												 *			Register
												 */
#define	AP_CPU_CONF			(CIU_BASE+0x0008)	/* 32 bit	AP CPU
												 *			Configuration
												 *			Register
												 */
#define	CP_CPU_SRAM_SPD		(CIU_BASE+0x000C)	/* 32 bit	CP CPU SRAM Speed
												 *			Config Register
												 */
#define	AP_CPU_SRAM_SPD		(CIU_BASE+0x0010)	/* 32 bit	AP CPU SRAM Speed
												 *			Config Register
												 */
#define	CP_CPU_L2C_SRAM_SPD	(CIU_BASE+0x0014)	/* 32 bit	CP CPU L2 Cache
												 *			SRAM Speed Config
												 *			Register
												 */
#define	AP_CPU_L2C_SRAM_SPD	(CIU_BASE+0x0018)	/* 32 bit	AP CPU L2 Cache
												 *			SRAM Speed Config
												 *			Register
												 */
#define	MCB_CONF			(CIU_BASE+0x001C)	/* 32 bit	MCB Configuration
												 *			Register
												 */
#define	SYS_BOOT_CNTRL		(CIU_BASE+0x0020)	/* 32 bit	System Boot Control
												 *			Register
												 */
#define	SW_BRANCH_ADDR		(CIU_BASE+0x0024)	/* 32 bit	Software Branch
												 *			Address Register
												 */
#define	PERF_COUNT0_CNTRL	(CIU_BASE+0x0028)	/* 32 bit	Performance Counter
												 *			0 Control Register
												 */
#define	PERF_COUNT1_CNTRL	(CIU_BASE+0x002C)	/* 32 bit	Performance Counter
												 *			1 Control Register
												 */
#define	PERF_COUNT2_CNTRL	(CIU_BASE+0x0030)	/* 32 bit	Performance Counter
												 *			2 Control Register
												 */
#define	PERF_COUNT0			(CIU_BASE+0x0034)	/* 32 bit	Performance Count 0
												 *			Register
												 */
#define	PERF_COUNT1			(CIU_BASE+0x0038)	/* 32 bit	Performance Count 1
												 *			Register
												 */
#define	PERF_COUNT2			(CIU_BASE+0x003C)	/* 32 bit	Performance Count 2
												 *			Register
												 */
#define	MC_CONF				(CIU_BASE+0x0040)	/* 32 bit	MC Configuration
												 *			Register
												 */

/*
 *
 *	THE BIT DEFINES
 *
 */
/*	CHIP_ID				0x0000	Chip ID Register */
/*		Bit(s) CHIP_ID_RSRV_31_24 reserved */
#define	CHIP_ID_REV_ID_MSK			SHIFT16(0xff)	/* Revision ID */
#define	CHIP_ID_REV_ID_BASE			16
#define	CHIP_ID_CHIP_ID_MSK			SHIFT0(0xffff)	/* Chip ID */
#define	CHIP_ID_CHIP_ID_BASE		0

/*	CP_CPU_CONF			0x0004	CP CPU Configuration Register */
/*		Bit(s) CP_CPU_CONF_RSRV_31_16 reserved */
#define	CP_CPU_CONF_BOOT_FROM			BIT_15			/* Boot from Status */
/*		Bit(s) CP_CPU_CONF_RSRV_14_13 reserved */
/* L2 Cache Transparent Mode */
#define	CP_CPU_CONF_L2C_TP_MODE			BIT_12			
/* L2 Cache ECC Check Enable */
#define	CP_CPU_CONF_L2C_ECC_CHK_EN		BIT_11			
#define	CP_CPU_CONF_REMAP_EN			BIT_10			/* DDR Shadow Re-Map Enable */
/* PCLK Wait for Interrupt Enable */
#define	CP_CPU_CONF_PCLK_WFI_EN			BIT_9			
#define	CP_CPU_CONF_SEL_MRVL_ID			BIT_8			/* Select Marvell ID */
#define	CP_CPU_CONF_CG_BPASS1			BIT_7			/* Clock Gate Bypass 1 */
#define	CP_CPU_CONF_CG_BPASS0			BIT_6			/* Clock Gate Bypass 0 */
#define	CP_CPU_CONF_AFIFO_MERGE_DIS		BIT_5			/* FIFO Merge Disable */
#define	CP_CPU_CONF_L2C_RAM_SEL			BIT_4			/* L2 Cache RAM Select */
#define	CP_CPU_CONF_L2C_EXIST			BIT_3			/* L2 Cache Enable */
#define	CP_CPU_CONF_L2C_WT_MODE			BIT_2			/* L2 Cache Write Mode */
/*		Bit(s) CP_CPU_CONF_RSRV_1 reserved */
#define	CP_CPU_CONF_VINITHI				BIT_0			/* Vector Init High */

/*	AP_CPU_CONF			0x0008	AP CPU Configuration Register */
/*		Bit(s) AP_CPU_CONF_RSRV_31_16 reserved */
#define	AP_CPU_CONF_BOOT_FROM			BIT_15			/* Boot from Status */
#define	AP_CPU_CONF_MMU_NOT_CA			BIT_14			/* L2C MMU Not Cacheable */
/* L2C No MMU Translation abort */
#define	AP_CPU_CONF_NO_TRANS_ABT		BIT_13			
/* L2 Cache Attribute Select */
#define	AP_CPU_CONF_L2C_ATTR_SEL		BIT_12			
/* L2 Cache ECC Check Enable */
#define	AP_CPU_CONF_L2C_ECC_CHK_EN		BIT_11			
#define	AP_CPU_CONF_REMAP_EN			BIT_10			/* DDR Shadow Re-Map Enable */
/* PCLK Wait for Interrupt Enable */
#define	AP_CPU_CONF_PCLK_WFI_EN			BIT_9			
#define	AP_CPU_CONF_SEL_MRVL_ID			BIT_8			/* Select Marvell ID */
#define	AP_CPU_CONF_CG_BPASS1			BIT_7			/* Clock Gate Bypass 1 */
#define	AP_CPU_CONF_CG_BPASS0			BIT_6			/* Clock Gate Bypass 0 */
#define	AP_CPU_CONF_AFIFO_MERGE_DIS		BIT_5			/* FIFO Merge Disable */
#define	AP_CPU_CONF_L2C_RAM_SEL			BIT_4			/* L2 Cache RAM Select */
#define	AP_CPU_CONF_L2C_EXIST			BIT_3			/* L2 Cache Enable */
#define	AP_CPU_CONF_L2C_WT_MODE			BIT_2			/* L2 Cache Write Mode */
#define	AP_CPU_CONF_NONMMU_MODE			BIT_1			/* Non-MMU Mode */
#define	AP_CPU_CONF_VINITHI				BIT_0			/* Vector Init High */

/*	CP_CPU_SRAM_SPD		0x000C	CP CPU SRAM Speed Config Register */
/*		Bit(s) CP_CPU_SRAM_SPD_RSRV_31_30 reserved */
#define	CP_CPU_SRAM_SPD_DTCM_RTC_MSK			SHIFT27(0x7)	/* DTCM RTC */
#define	CP_CPU_SRAM_SPD_DTCM_RTC_BASE			27
#define	CP_CPU_SRAM_SPD_ITCM_RTC_MSK			SHIFT24(0x7)	/* ITCM RTC */
#define	CP_CPU_SRAM_SPD_ITCM_RTC_BASE			24
#define	CP_CPU_SRAM_SPD_BPM_WTC_MSK				SHIFT21(0x7)	/* BPM WTC */
#define	CP_CPU_SRAM_SPD_BPM_WTC_BASE			21
#define	CP_CPU_SRAM_SPD_BPM_RTC_MSK				SHIFT19(0x3)	/* BPM RTC */
#define	CP_CPU_SRAM_SPD_BPM_RTC_BASE			19
#define	CP_CPU_SRAM_SPD_DC_DIRTY_WTC_MSK		SHIFT16(0x7)	/* DC Dirty WTC */
#define	CP_CPU_SRAM_SPD_DC_DIRTY_WTC_BASE		16
#define	CP_CPU_SRAM_SPD_DC_DIRTY_RTC_MSK		SHIFT14(0x3)	/* DC Dirty RTC */
#define	CP_CPU_SRAM_SPD_DC_DIRTY_RTC_BASE		14
#define	CP_CPU_SRAM_SPD_DC_TAG_WTC_MSK			SHIFT11(0x7)	/* DC Tag WTC */
#define	CP_CPU_SRAM_SPD_DC_TAG_WTC_BASE			11
#define	CP_CPU_SRAM_SPD_DC_TAG_RTC_MSK			SHIFT9(0x3)		/* DC Tag RTC */
#define	CP_CPU_SRAM_SPD_DC_TAG_RTC_BASE			9
#define	CP_CPU_SRAM_SPD_DC_DATA_RTC_MSK			SHIFT6(0x7)		/* DC Data RTC */
#define	CP_CPU_SRAM_SPD_DC_DATA_RTC_BASE		6
#define	CP_CPU_SRAM_SPD_IC_TAG_RTC_MSK			SHIFT3(0x7)		/* IC Tag RTC */
#define	CP_CPU_SRAM_SPD_IC_TAG_RTC_BASE			3
#define	CP_CPU_SRAM_SPD_IC_DATA_RTC_MSK			SHIFT0(0x7)		/* IC Data RTC */
#define	CP_CPU_SRAM_SPD_IC_DATA_RTC_BASE		0

/*	AP_CPU_SRAM_SPD		0x0010	AP CPU SRAM Speed Config Register */
/*		Bit(s) AP_CPU_SRAM_SPD_RSRV_31_29 reserved */
#define	AP_CPU_SRAM_SPD_TLB_WTC_MSK				SHIFT26(0x7)	/* TLB WTC */
#define	AP_CPU_SRAM_SPD_TLB_WTC_BASE			26
#define	AP_CPU_SRAM_SPD_TLB_RTC_MSK				SHIFT24(0x3)	/* TLB RTC */
#define	AP_CPU_SRAM_SPD_TLB_RTC_BASE			24
#define	AP_CPU_SRAM_SPD_BPM_WTC_MSK				SHIFT21(0x7)	/* BPM WTC */
#define	AP_CPU_SRAM_SPD_BPM_WTC_BASE			21
#define	AP_CPU_SRAM_SPD_BPM_RTC_MSK				SHIFT19(0x3)	/* BPM RTC */
#define	AP_CPU_SRAM_SPD_BPM_RTC_BASE			19
#define	AP_CPU_SRAM_SPD_DC_DIRTY_WTC_MSK		SHIFT16(0x7)	/* DC Dirty WTC */
#define	AP_CPU_SRAM_SPD_DC_DIRTY_WTC_BASE		16
#define	AP_CPU_SRAM_SPD_DC_DIRTY_RTC_MSK		SHIFT14(0x3)	/* DC Dirty RTC */
#define	AP_CPU_SRAM_SPD_DC_DIRTY_RTC_BASE		14
#define	AP_CPU_SRAM_SPD_DC_TAG_WTC_MSK			SHIFT11(0x7)	/* DC Tag WTC */
#define	AP_CPU_SRAM_SPD_DC_TAG_WTC_BASE			11
#define	AP_CPU_SRAM_SPD_DC_TAG_RTC_MSK			SHIFT9(0x3)		/* DC TAG RTC */
#define	AP_CPU_SRAM_SPD_DC_TAG_RTC_BASE			9
#define	AP_CPU_SRAM_SPD_DC_DATA_RTC_MSK			SHIFT6(0x7)		/* DC Data RTC */
#define	AP_CPU_SRAM_SPD_DC_DATA_RTC_BASE		6
#define	AP_CPU_SRAM_SPD_IC_TAG_RTC_MSK			SHIFT3(0x7)		/* IC Tag RTC */
#define	AP_CPU_SRAM_SPD_IC_TAG_RTC_BASE			3
#define	AP_CPU_SRAM_SPD_IC_DATA_RTC_MSK			SHIFT0(0x7)		/* IC Data RTC */
#define	AP_CPU_SRAM_SPD_IC_DATA_RTC_BASE		0

/*	CP_CPU_L2C_SRAM_SPD	0x0014	CP CPU L2 Cache SRAM Speed Config Register */
/*		Bit(s) CP_CPU_L2C_SRAM_SPD_RSRV_31_30 reserved */
#define	CP_CPU_L2C_SRAM_SPD_DATA_RAM_RTC_MSK		SHIFT27(0x7)	/* Data RAM RTC */
#define	CP_CPU_L2C_SRAM_SPD_DATA_RAM_RTC_BASE		27
#define	CP_CPU_L2C_SRAM_SPD_DATA_RAM_WTC_MSK		SHIFT25(0x3)	/* Data RAM WTC */
#define	CP_CPU_L2C_SRAM_SPD_DATA_RAM_WTC_BASE		25
/* Dirty RAM RTC */
#define	CP_CPU_L2C_SRAM_SPD_DIRTY_RAM_RTC_MSK		SHIFT23(0x3)	
#define	CP_CPU_L2C_SRAM_SPD_DIRTY_RAM_RTC_BASE		23
/* Dirty RAM WTC */
#define	CP_CPU_L2C_SRAM_SPD_DIRTY_RAM_WTC_MSK		SHIFT20(0x7)	
#define	CP_CPU_L2C_SRAM_SPD_DIRTY_RAM_WTC_BASE		20
#define	CP_CPU_L2C_SRAM_SPD_ECC_RAM_RTC_MSK			SHIFT17(0x7)	/* ERR RAM RTC */
#define	CP_CPU_L2C_SRAM_SPD_ECC_RAM_RTC_BASE		17
#define	CP_CPU_L2C_SRAM_SPD_ECC_RAM_WTC_MSK			SHIFT15(0x3)	/* ECC RAM WTC */
#define	CP_CPU_L2C_SRAM_SPD_ECC_RAM_WTC_BASE		15
#define	CP_CPU_L2C_SRAM_SPD_TAG_RAM_RTC_MSK			SHIFT13(0x3)	/* Tag RAM RTC */
#define	CP_CPU_L2C_SRAM_SPD_TAG_RAM_RTC_BASE		13
#define	CP_CPU_L2C_SRAM_SPD_TAG_RAM_WTC_MSK			SHIFT10(0x7)	/* Tag RAM WTC */
#define	CP_CPU_L2C_SRAM_SPD_TAG_RAM_WTC_BASE		10
/* Valid RAM RTC */
#define	CP_CPU_L2C_SRAM_SPD_VALID_RAM_RTC_MSK		SHIFT8(0x3)		
#define	CP_CPU_L2C_SRAM_SPD_VALID_RAM_RTC_BASE		8
/* Valid RAM WTC */
#define	CP_CPU_L2C_SRAM_SPD_VALID_RAM_WTC_MSK		SHIFT5(0x7)		
#define	CP_CPU_L2C_SRAM_SPD_VALID_RAM_WTC_BASE		5
#define	CP_CPU_L2C_SRAM_SPD_LOCK_RAM_RTC_MSK		SHIFT3(0x3)		/* Lock RAM RTC */
#define	CP_CPU_L2C_SRAM_SPD_LOCK_RAM_RTC_BASE		3
#define	CP_CPU_L2C_SRAM_SPD_LOCK_RAM_WTC_MSK		SHIFT0(0x7)		/* Lock RAM WTC */
#define	CP_CPU_L2C_SRAM_SPD_LOCK_RAM_WTC_BASE		0

/*	AP_CPU_L2C_SRAM_SPD	0x0018	AP CPU L2 Cache SRAM Speed Config Register */
/*		Bit(s) AP_CPU_L2C_SRAM_SPD_RSRV_31_30 reserved */
#define	AP_CPU_L2C_SRAM_SPD_DATA_RAM_RTC_MSK		SHIFT27(0x7)	/* Data RAM RTC */
#define	AP_CPU_L2C_SRAM_SPD_DATA_RAM_RTC_BASE		27
#define	AP_CPU_L2C_SRAM_SPD_DATA_RAM_WTC_MSK		SHIFT25(0x3)	/* Data RAM WTC */
#define	AP_CPU_L2C_SRAM_SPD_DATA_RAM_WTC_BASE		25
/* Dirty RAM RTC */
#define	AP_CPU_L2C_SRAM_SPD_DIRTY_RAM_RTC_MSK		SHIFT23(0x3)	
#define	AP_CPU_L2C_SRAM_SPD_DIRTY_RAM_RTC_BASE		23
/* Dirty RAM WTC */
#define	AP_CPU_L2C_SRAM_SPD_DIRTY_RAM_WTC_MSK		SHIFT20(0x7)	
#define	AP_CPU_L2C_SRAM_SPD_DIRTY_RAM_WTC_BASE		20
#define	AP_CPU_L2C_SRAM_SPD_ECC_RAM_RTC_MSK			SHIFT17(0x7)	/* ERR RAM RTC */
#define	AP_CPU_L2C_SRAM_SPD_ECC_RAM_RTC_BASE		17
#define	AP_CPU_L2C_SRAM_SPD_ECC_RAM_WTC_MSK			SHIFT15(0x3)	/* ECC RAM WTC */
#define	AP_CPU_L2C_SRAM_SPD_ECC_RAM_WTC_BASE		15
#define	AP_CPU_L2C_SRAM_SPD_TAG_RAM_RTC_MSK			SHIFT13(0x3)	/* Tag RAM RTC */
#define	AP_CPU_L2C_SRAM_SPD_TAG_RAM_RTC_BASE		13
#define	AP_CPU_L2C_SRAM_SPD_TAG_RAM_WTC_MSK			SHIFT10(0x7)	/* Tag RAM WTC */
#define	AP_CPU_L2C_SRAM_SPD_TAG_RAM_WTC_BASE		10
/* Valid RAM RTC */
#define	AP_CPU_L2C_SRAM_SPD_VALID_RAM_RTC_MSK		SHIFT8(0x3)		
#define	AP_CPU_L2C_SRAM_SPD_VALID_RAM_RTC_BASE		8
/* Valid RAM WTC */
#define	AP_CPU_L2C_SRAM_SPD_VALID_RAM_WTC_MSK		SHIFT5(0x7)		
#define	AP_CPU_L2C_SRAM_SPD_VALID_RAM_WTC_BASE		5
#define	AP_CPU_L2C_SRAM_SPD_LOCK_RAM_RTC_MSK		SHIFT3(0x3)		/* Lock RAM RTC */
#define	AP_CPU_L2C_SRAM_SPD_LOCK_RAM_RTC_BASE		3
#define	AP_CPU_L2C_SRAM_SPD_LOCK_RAM_WTC_MSK		SHIFT0(0x7)		/* Lock RAM WTC */
#define	AP_CPU_L2C_SRAM_SPD_LOCK_RAM_WTC_BASE		0

/*	MCB_CONF			0x001C	MCB Configuration Register */
/*		Bit(s) MCB_CONF_RSRV_31_20 reserved */
#define	MCB_CONF_MCB2_CLK_GATE_EN		BIT_19			/* MCB2 Clock Gating Enable */
#define	MCB_CONF_MCB1_CLK_GATE_EN		BIT_18			/* MCB1 Clock Gating Enable */
#define	MCB_CONF_MCB2_CLK_STOP_EN		BIT_17			/* MCB2 Clock Stop Enable */
#define	MCB_CONF_MCB1_CLK_STOP_EN		BIT_16			/* MCB1 Clock Stop Enable */
/*		Bit(s) MCB_CONF_RSRV_15_11 reserved */
#define	MCB_CONF_MCB1_S7_PRI			BIT_10			/* MCB1 s7 Port Priority */
#define	MCB_CONF_MCB1_S5_PRI			BIT_9			/* MCB1 s5 Port Priority */
#define	MCB_CONF_MCB1_S0_PRI			BIT_8			/* MCB1 S0 Port Priority */
/*		Bit(s) MCB_CONF_RSRV_7 reserved */
#define	MCB_CONF_MCB2_S7_SEL			BIT_6			/* MCB s7 Select */
#define	MCB_CONF_MCB2_S5_SEL			BIT_5			/* MCB s5 Select */
#define	MCB_CONF_MCB2_S0_SEL			BIT_4			/* MCB s0 Select */
/*		Bit(s) MCB_CONF_RSRV_3 reserved */
#define	MCB_CONF_MCB1_S7_ENB			BIT_2			/* MCB1 s7 Port Enable */
#define	MCB_CONF_MCB1_S5_ENB			BIT_1			/* MCB1 s5 Port Enable */
#define	MCB_CONF_MCB1_S0_ENB			BIT_0			/* MCB1 s0 Port Enable */

/*	SYS_BOOT_CNTRL		0x0020	System Boot Control Register */
/*		Bit(s) SYS_BOOT_CNTRL_RSRV_31_26 reserved */
/* Boot Platform State */
#define	SYS_BOOT_CNTRL_BOOT_PLTFM_STATE_MSK			SHIFT22(0xf)	
#define	SYS_BOOT_CNTRL_BOOT_PLTFM_STATE_BASE		22
/* Secure Download Enable */
#define	SYS_BOOT_CNTRL_SDE							BIT_21			
/* Secure Boot Enable */
#define	SYS_BOOT_CNTRL_SBE							BIT_20			
/* Download Disable */
#define	SYS_BOOT_CNTRL_DOWNLOAD_DISABLE				BIT_19			
/* DDR Initialized */
#define	SYS_BOOT_CNTRL_DDR_INITIALIZED				BIT_18			
#define	SYS_BOOT_CNTRL_PORT_ENA						BIT_17			/* Port Enable */
#define	SYS_BOOT_CNTRL_USB_WAKEUP					BIT_16			/* USB Wakeup */
/* Resume from Sleep */
#define	SYS_BOOT_CNTRL_RESUME_FROM_SLEEP			BIT_15			
/*		Bit(s) SYS_BOOT_CNTRL_RSRV_14 reserved */
#define	SYS_BOOT_CNTRL_USB_PORT						BIT_13			/* USB Port */
#define	SYS_BOOT_CNTRL_UART_PORT					BIT_12			/* UART Port */
/*		Bit(s) SYS_BOOT_CNTRL_RSRV_11_7 reserved */
#define	SYS_BOOT_CNTRL_JTAG_DISABLE					BIT_6			/* JTAG Disable */
/* CADDO Disable */
#define	SYS_BOOT_CNTRL_CADDO_DISABLE				BIT_5			
/*		Bit(s) SYS_BOOT_CNTRL_RSRV_4_1 reserved */
#define	SYS_BOOT_CNTRL_DEBUG_EN						BIT_0			/* Debug Enable */

/*	SW_BRANCH_ADDR		0x0024	Software Branch Address Register */
#define	SW_BRANCH_ADDR_BRANCH_ADDR_MSK		SHIFT0(0xffffffff)	/* Branch Address */
#define	SW_BRANCH_ADDR_BRANCH_ADDR_BASE		0

/*	PERF_COUNT0_CNTRL	0x0028	Performance Counter 0 Control Register */
/*		Bit(s) PERF_COUNT0_CNTRL_RSRV_31_11 reserved */
/* MCB1 Qu Threshold */
#define	PERF_COUNT0_CNTRL_MCB1_QU_THRE_MSK				SHIFT8(0x7)			
#define	PERF_COUNT0_CNTRL_MCB1_QU_THRE_BASE				8
/* MCB1 Qu below thre Count Enable */
#define	PERF_COUNT0_CNTRL_MCB1_QU_BEL_THRE_CNT_EN		BIT_7				
/* MCB1 Qu threshold Count Enable */
#define	PERF_COUNT0_CNTRL_MCB1_QU_ABV_THRE_CNT_EN		BIT_6				
/* MCB1 Idle Count Enable */
#define	PERF_COUNT0_CNTRL_MCB1_IDLE_CNT_EN				BIT_5				
/* MCB1 Qu Full Count Enable */
#define	PERF_COUNT0_CNTRL_MCB1_QU_FULL_CNT_EN			BIT_4				
/* MCB1 Qu Empty Count Enable */
#define	PERF_COUNT0_CNTRL_MCB1_QU_EMPTY_CNT_EN			BIT_3				
/* Read Byte Count Enable */
#define	PERF_COUNT0_CNTRL_S0_RD_BYTE_COUNT_EN			BIT_2				
/* Write Byte Count Enable */
#define	PERF_COUNT0_CNTRL_S0_WR_BYTE_COUNT_EN			BIT_1				
/* Clear Counter */
#define	PERF_COUNT0_CNTRL_CLR_COUNT						BIT_0				

/*	PERF_COUNT1_CNTRL	0x002C	Performance Counter 1 Control Register */
/*		Bit(s) PERF_COUNT1_CNTRL_RSRV_31_11 reserved */
/* MCB2 Qu Threshold */
#define	PERF_COUNT1_CNTRL_MCB2_QU_THRE_MSK				SHIFT8(0x7)			
#define	PERF_COUNT1_CNTRL_MCB2_QU_THRE_BASE				8
/* MCB2 Qu below thre Count Enable */
#define	PERF_COUNT1_CNTRL_MCB2_QU_BEL_THRE_CNT_EN		BIT_7				
/* MCB2 Qu above thre Count Enable */
#define	PERF_COUNT1_CNTRL_MCB2_QU_ABV_THRE_CNT_EN		BIT_6				
/* MCB2 Idle Count Enable */
#define	PERF_COUNT1_CNTRL_MCB2_IDLE_CNT_EN				BIT_5				
/* MCB2 Qu Full Count Enable */
#define	PERF_COUNT1_CNTRL_MCB2_QU_FULL_CNT_EN			BIT_4				
/* MCB2 Qu Empty Count Enable */
#define	PERF_COUNT1_CNTRL_MCB2_QU_EMPTY_CNT_EN			BIT_3				
/* Read Byte Count Enable */
#define	PERF_COUNT1_CNTRL_S5_RD_BYTE_COUNT_EN			BIT_2				
/* Write Byte Count Enable */
#define	PERF_COUNT1_CNTRL_S5_WR_BYTE_COUNT_EN			BIT_1				
/* Clear Counter */
#define	PERF_COUNT1_CNTRL_CLR_COUNT						BIT_0				

/*	PERF_COUNT2_CNTRL	0x0030	Performance Counter 2 Control Register */
/*		Bit(s) PERF_COUNT2_CNTRL_RSRV_31_4 reserved */
/*		Bit(s) PERF_COUNT2_CNTRL_RSRV_3 reserved */
/* Read Byte Count Enable */
#define	PERF_COUNT2_CNTRL_S7_RD_BYTE_COUNT_EN		BIT_2				
/* Write Byte Count Enable */
#define	PERF_COUNT2_CNTRL_S7_WR_BYTE_COUNT_EN		BIT_1				
/* Clear Counter */
#define	PERF_COUNT2_CNTRL_CLR_COUNT					BIT_0				

/*	PERF_COUNT0			0x0034	Performance Count 0 Register */
#define	PERF_COUNT0_COUT_VALUE_MSK		SHIFT0(0xffffffff)	/* Count Value */
#define	PERF_COUNT0_COUT_VALUE_BASE		0

/*	PERF_COUNT1			0x0038	Performance Count 1 Register */
#define	PERF_COUNT1_COUT_VALUE_MSK		SHIFT0(0xffffffff)	/* Count Value */
#define	PERF_COUNT1_COUT_VALUE_BASE		0

/*	PERF_COUNT2			0x003C	Performance Count 2 Register */
#define	PERF_COUNT2_COUT_VALUE_MSK		SHIFT0(0xffffffff)	/* Count Value */
#define	PERF_COUNT2_COUT_VALUE_BASE		0

/*	MC_CONF				0x0040	MC Configuration Register */
/*		Bit(s) MC_CONF_RSRV_31_4 reserved */
/*		Bit(s) MC_CONF_RSRV_3_2 reserved */
#define	MC_CONF_MC_PHY_DLL_DIS		BIT_1				/* MC Phy DLL Disable */
#define	MC_CONF_MC_PHY_PLL_DIS		BIT_0				/* MC Phy PLL Disable */



/* -------------------- */


#endif	/* __INC_CIU_H */
