/******************************************************************************
 *
 * Name:	KPC.h
 * Project:	Hermon-2
 * Purpose:	Testing
 *
 ******************************************************************************/

/******************************************************************************
 *
 *  (C)Copyright 2005 - 2011 Marvell. All Rights Reserved.
 *  
 *  THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF MARVELL.
 *  The copyright notice above does not evidence any actual or intended 
 *  publication of such source code.
 *  This Module contains Proprietary Information of Marvell and should be
 *  treated as Confidential.
 *  The information in this file is provided for the exclusive use of the 
 *  licensees of Marvell.
 *  Such users have the right to use, modify, and incorporate this code into 
 *  products for purposes authorized by the license agreement provided they 
 *  include this notice and the associated copyright notice with any such
 *  product. 
 *  The information in this file is provided "AS IS" without warranty.
 *
 ******************************************************************************/

/******************************************************************************
 *
 * This file was automatically generated by reg.pl using  *	KPC.csv
 *
 ******************************************************************************/

/******************************************************************************
 *
 * History:
 *
 ********* PLEASE INSERT THE CVS HISTORY OF THE PREVIOUS VERSION HERE. *********
 *******************************************************************************/

#ifndef	__INC_KPC_H
#define	__INC_KPC_H


/*
 *
 *	THE BASE ADDRESSES
 *
 */
#define	KPC_BASE	0xD4012000

/*
 *
 *	THE REGISTER DEFINES
 *
 */
#define	KPC_PC		(KPC_BASE+0x0000)	/* 32 bit	Keypad Control Register */
#define	KPC_DK		(KPC_BASE+0x0008)	/* 32 bit	Keypad Direct Key Register */
#define	KPC_REC		(KPC_BASE+0x0010)	/* 32 bit	Keypad Rotary Encoder Count
										 *			Register
										 */
#define	KPC_MK		(KPC_BASE+0x0018)	/* 32 bit	Keypad Matrix Key Register */
#define	KPC_AS		(KPC_BASE+0x0020)	/* 32 bit	Keypad Automatic Scan
										 *			Register
										 */
#define	KPC_ASMKP0	(KPC_BASE+0x0028)	/* 32 bit	Keypad Automatic Scan
										 *			Multiple Keypress
										 *			Register 0 
										 */
#define	KPC_ASMKP1	(KPC_BASE+0x0030)	/* 32 bit	Keypad Automatic Scan
										 *			Multiple Keypress
										 *			Register 1 
										 */
#define	KPC_ASMKP2	(KPC_BASE+0x0038)	/* 32 bit	Keypad Automatic Scan
										 *			Multiple Keypress
										 *			Register 2 
										 */
#define	KPC_ASMKP3	(KPC_BASE+0x0040)	/* 32 bit	Keypad Automatic Scan
										 *			Multiple Keypress
										 *			Register 3 
										 */
#define	KPC_KDI		(KPC_BASE+0x0048)	/* 32 bit	Keypad Key Debounce
										 *			Interval Register
										 */

/*
 *
 *	THE BIT DEFINES
 *
 */
/*	KPC_PC		0x0000	Keypad Control Register */
/*		Bit(s) KPC_PC_RSRV_31 reserved */
#define	KPC_PC_AS				BIT_30			/* Automatic Scan */
#define	KPC_PC_ASACT			BIT_29			/* Automatic Scan on Activity */
#define	KPC_PC_MKRN_MSK			SHIFT26(0x7)	/* Matrix Keypad Row Number */
#define	KPC_PC_MKRN_BASE		26
#define	KPC_PC_MKCN_MSK			SHIFT23(0x7)	/* Keypad Column Number */
#define	KPC_PC_MKCN_BASE		23
#define	KPC_PC_MI				BIT_22			/* Matrix Keypad Interrupt */
#define	KPC_PC_IMKP				BIT_21			/* Ignore Multiple Keypress */
#define	KPC_PC_MS7				BIT_20			/* Manual Matrix Scan line 7 */
#define	KPC_PC_MS6				BIT_19			/* Manual Matrix Scan line 6 */
#define	KPC_PC_MS5				BIT_18			/* Manual Matrix Scan line 5 */
#define	KPC_PC_MS4				BIT_17			/* Manual Matrix Scan line 4 */
#define	KPC_PC_MS3				BIT_16			/* Manual Matrix Scan line 3 */
#define	KPC_PC_MS2				BIT_15			/* Manual Matrix Scan line 2 */
#define	KPC_PC_MS1				BIT_14			/* Manual Matrix Scan line 1 */
#define	KPC_PC_MS0				BIT_13			/* Manual Matrix Scan line 0 */
#define	KPC_PC_ME				BIT_12			/* Matrix Keypad Enable */
#define	KPC_PC_MIE				BIT_11			/* Matrix Interrupt Enable */
/*		Bit(s) KPC_PC_RSRV_10 reserved */
#define	KPC_PC_DK_DEB_SEL		BIT_9			/* Direct Keypad Debounce Select */
#define	KPC_PC_DN_MSK			SHIFT6(0x7)		/* Direct Key Number */
#define	KPC_PC_DN_BASE			6
#define	KPC_PC_DI				BIT_5			/* Direct Keypad Interrupt */
/* Rotary Encoder Zero Debounce Interval */
#define	KPC_PC_RE_ZERO_DEB		BIT_4			
#define	KPC_PC_REE1				BIT_3			/* Rotary Encoder 1 Enable */
#define	KPC_PC_REE0				BIT_2			/* Rotary Encoder 0 Enable */
#define	KPC_PC_DE				BIT_1			/* Direct Keypad Enable */
#define	KPC_PC_DIE				BIT_0			/* Direct Keypad Interrupt Enable */

/*	KPC_DK		0x0008	Keypad Direct Key Register */
#define	KPC_DK_DKP					BIT_31				/* Direct Key Pressed */
/*		Bit(s) KPC_DK_RSRV_30_8 reserved */
#define	KPC_DK_DK7					BIT_7				/* Direct Key 7 input */
#define	KPC_DK_DK6					BIT_6				/* Direct Key 6 input */
#define	KPC_DK_DK5					BIT_5				/* Direct Key 5 input */
#define	KPC_DK_DK4					BIT_4				/* Direct Key 4 input */
/* Rotary Encoder B / Direct Key 3 input */
#define	KPC_DK_RB1_DK3				BIT_3				
/* Rotary Encoder A / Direct Key 2 input */
#define	KPC_DK_RA1_DK2				BIT_2				
/* Rotary Encoder B / Direct Key 1 input */
#define	KPC_DK_RB0_DK1				BIT_1				
/* Rotary Encoder A / Direct Key 0 input */
#define	KPC_DK_RA0_DK0				BIT_0				

/*	KPC_REC		0x0010	Keypad Rotary Encoder Count Register */
/* Overflow bit for rotary encoder 1 */
#define	KPC_REC_OF1					BIT_31			
/* Underflow bit for rotary encoder 1 */
#define	KPC_REC_UF1					BIT_30			
/*		Bit(s) KPC_REC_RSRV_29_24 reserved */
/* Count value for rotary encoder 1 */
#define	KPC_REC_RE_COUNT1_MSK		SHIFT16(0xff)	
#define	KPC_REC_RE_COUNT1_BASE		16
/* Overflow bit for rotary encoder 0 */
#define	KPC_REC_OF0					BIT_15			
/* Underflow bit for rotary encoder 0 */
#define	KPC_REC_UF0					BIT_14			
/*		Bit(s) KPC_REC_RSRV_13_8 reserved */
/* Count value for rotary encoder 0 */
#define	KPC_REC_RE_COUNT0_MSK		SHIFT0(0xff)	
#define	KPC_REC_RE_COUNT0_BASE		0

/*	KPC_MK		0x0018	Keypad Matrix Key Register */
#define	KPC_MK_MKP					BIT_31				/* MKP */
/*		Bit(s) KPC_MK_RSRV_30_8 reserved */
#define	KPC_MK_MR7					BIT_7				/* Matrix Row 7 */
#define	KPC_MK_MR6					BIT_6				/* Matrix Row 6 */
#define	KPC_MK_MR5					BIT_5				/* Matrix Row 5 */
#define	KPC_MK_MR4					BIT_4				/* Matrix Row 4 */
#define	KPC_MK_MR3					BIT_3				/* Matrix Row 3 */
#define	KPC_MK_MR2					BIT_2				/* Matrix Row 2 */
#define	KPC_MK_MR1					BIT_1				/* Matrix Row 1 */
#define	KPC_MK_MR0					BIT_0				/* Matrix Row 0 */

/*	KPC_AS		0x0020	Keypad Automatic Scan Register */
#define	KPC_AS_SO					BIT_31			/* Scan On */
#define	KPC_AS_MUKP_MSK				SHIFT26(0x1f)	/* Multiple Keys Pressed */
#define	KPC_AS_MUKP_BASE			26
/*		Bit(s) KPC_AS_RSRV_25_8 reserved */
#define	KPC_AS_RP_MSK				SHIFT4(0xf)		/* Row Pressed */
#define	KPC_AS_RP_BASE				4
#define	KPC_AS_CP_MSK				SHIFT0(0xf)		/* Column Pressed */
#define	KPC_AS_CP_BASE				0

/*	KPC_ASMKP0	0x0028	Keypad Automatic Scan Multiple Keypress Register 0 */
#define	KPC_ASMKP0_SO					BIT_31			/* SO */
/*		Bit(s) KPC_ASMKP0_RSRV_30_24 reserved */
/* Matrix Keypad Column 1 reading */
#define	KPC_ASMKP0_MKC1_MSK				SHIFT16(0xff)	
#define	KPC_ASMKP0_MKC1_BASE			16
/*		Bit(s) KPC_ASMKP0_RSRV_15_8 reserved */
/* Matrix Keypad Column 0 reading */
#define	KPC_ASMKP0_MKC0_MSK				SHIFT0(0xff)	
#define	KPC_ASMKP0_MKC0_BASE			0

/*	KPC_ASMKP1	0x0030	Keypad Automatic Scan Multiple Keypress Register 1 */
#define	KPC_ASMKP1_SO					BIT_31			/* Scan On */
/*		Bit(s) KPC_ASMKP1_RSRV_30_24 reserved */
/* Matrix Keypad Column 3 Reading */
#define	KPC_ASMKP1_MKC3_MSK				SHIFT16(0xff)	
#define	KPC_ASMKP1_MKC3_BASE			16
/*		Bit(s) KPC_ASMKP1_RSRV_15_8 reserved */
/* Matrix Keypad Column 2 Reading */
#define	KPC_ASMKP1_MKC2_MSK				SHIFT0(0xff)	
#define	KPC_ASMKP1_MKC2_BASE			0

/*	KPC_ASMKP2	0x0038	Keypad Automatic Scan Multiple Keypress Register 2 */
#define	KPC_ASMKP2_SO					BIT_31			/* SO */
/*		Bit(s) KPC_ASMKP2_RSRV_30_24 reserved */
/* Matrix Keypad Column 5 reading */
#define	KPC_ASMKP2_MKC5_MSK				SHIFT16(0xff)	
#define	KPC_ASMKP2_MKC5_BASE			16
/*		Bit(s) KPC_ASMKP2_RSRV_15_8 reserved */
/* Matrix Keypad Column 4 reading */
#define	KPC_ASMKP2_MKC4_MSK				SHIFT0(0xff)	
#define	KPC_ASMKP2_MKC4_BASE			0

/*	KPC_ASMKP3	0x0040	Keypad Automatic Scan Multiple Keypress Register 3 */
#define	KPC_ASMKP3_SO					BIT_31			/* SO */
/*		Bit(s) KPC_ASMKP3_RSRV_30_24 reserved */
/* Matrix Keypad Column 7 reading */
#define	KPC_ASMKP3_MKC7_MSK				SHIFT16(0xff)	
#define	KPC_ASMKP3_MKC7_BASE			16
/*		Bit(s) KPC_ASMKP3_RSRV_15_8 reserved */
/* Matrix Keypad Column 6 reading */
#define	KPC_ASMKP3_MKC6_MSK				SHIFT0(0xff)	
#define	KPC_ASMKP3_MKC6_BASE			0

/*	KPC_KDI		0x0048	Keypad Key Debounce Interval Register */
/*		Bit(s) KPC_KDI_RSRV_31_16 reserved */
/* Direct Key Debounce Interval */
#define	KPC_KDI_DIRECT_KEY_DEBOUNCE_INTERVAL_MSK		SHIFT8(0xff)	
#define	KPC_KDI_DIRECT_KEY_DEBOUNCE_INTERVAL_BASE		8
/* Matrix Key Debounce Interval */
#define	KPC_KDI_MATRIX_KEY_DEBOUNCE_INTERVAL_MSK		SHIFT0(0xff)	
#define	KPC_KDI_MATRIX_KEY_DEBOUNCE_INTERVAL_BASE		0



/* -------------------- */


#endif	/* __INC_KPC_H */
